#!/usr/bin/env python3
"""Scaffold API route files for Express, FastAPI, or Gin."""
import argparse
from pathlib import Path


HTTP_METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE"}
FRAMEWORKS = {"express", "fastapi", "gin"}


def ensure_file(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


# ---------- Express (Node.js) templates ----------

def build_express_templates(route_name: str, method: str) -> dict:
    route_var = route_name.replace("-", "_")
    route_pascal = "".join(p.capitalize() for p in route_name.split("-"))

    controller = f"""\
// Auto-generated by api_route_scaffolder.py
const {route_var}Service = require('../services/{route_name}.service');

async function {route_var}Handler(req, res) {{
  const result = await {route_var}Service.{route_var}({{
    params: req.params,
    query: req.query,
    body: req.body
  }});

  return res.status(200).json({{
    data: result,
    error: null,
    meta: {{ route: '{route_name}', method: '{method}' }}
  }});
}}

module.exports = {{ {route_var}Handler }};
"""

    service = f"""\
// Auto-generated by api_route_scaffolder.py
async function {route_var}(input) {{
  // TODO: implement business logic
  return {{ ok: true, input }};
}}

module.exports = {{ {route_var} }};
"""

    dto = f"""\
// Auto-generated by api_route_scaffolder.py
const z = require('zod');

const {route_pascal}Dto = z.object({{
  // TODO: define schema
}});

module.exports = {{ {route_pascal}Dto }};
"""

    route = f"""\
// Auto-generated by api_route_scaffolder.py
const router = require('express').Router();
const {{ {route_var}Handler }} = require('../controllers/{route_name}.controller');

router.{method.lower()}('/{route_name}', {route_var}Handler);

module.exports = router;
"""

    test = f"""\
// Auto-generated by api_route_scaffolder.py
describe('{method} /{route_name}', () => {{
  it('returns standardized envelope', async () => {{
    // TODO: add framework-specific integration test
    expect(true).toBe(true);
  }});
}});
"""

    return {"controller": controller, "service": service, "dto": dto, "route": route, "test": test}


# ---------- FastAPI (Python) templates ----------

def build_fastapi_templates(route_name: str, method: str) -> dict:
    route_var = route_name.replace("-", "_")
    route_pascal = "".join(p.capitalize() for p in route_name.split("-"))
    http_method = method.lower()

    router_file = f"""\
# Auto-generated by api_route_scaffolder.py
from fastapi import APIRouter, HTTPException
from .schemas.{route_var} import {route_pascal}Request, {route_pascal}Response
from .services.{route_var}_service import {route_var}_service

router = APIRouter(prefix="/{route_name}", tags=["{route_name}"])


@router.{http_method}("/", response_model={route_pascal}Response)
async def {route_var}_handler(payload: {route_pascal}Request):
    return await {route_var}_service(payload)
"""

    service = f"""\
# Auto-generated by api_route_scaffolder.py
from .schemas.{route_var} import {route_pascal}Request, {route_pascal}Response


async def {route_var}_service(payload: {route_pascal}Request) -> {route_pascal}Response:
    # TODO: implement business logic
    return {route_pascal}Response(ok=True)
"""

    schema = f"""\
# Auto-generated by api_route_scaffolder.py
from pydantic import BaseModel


class {route_pascal}Request(BaseModel):
    pass  # TODO: define fields


class {route_pascal}Response(BaseModel):
    ok: bool
"""

    test = f"""\
# Auto-generated by api_route_scaffolder.py
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)


def test_{route_var}_returns_ok():
    resp = client.{http_method}("/{route_name}/")
    assert resp.status_code == 200
"""

    return {"router": router_file, "service": service, "schema": schema, "test": test}


# ---------- Gin (Go) templates ----------

def build_gin_templates(route_name: str, method: str) -> dict:
    route_pascal = "".join(p.capitalize() for p in route_name.split("-"))

    handler = f"""\
// Auto-generated by api_route_scaffolder.py
package handlers

import (
\t"net/http"
\t"github.com/gin-gonic/gin"
)

func {route_pascal}Handler(c *gin.Context) {{
\t// TODO: implement logic
\tc.JSON(http.StatusOK, gin.H{{
\t\t"data":  nil,
\t\t"error": nil,
\t}})
}}
"""

    route = f"""\
// Auto-generated by api_route_scaffolder.py
package routes

import (
\t"github.com/gin-gonic/gin"
\t"your-module/handlers"
)

func Register{route_pascal}Routes(r *gin.Engine) {{
\tr.{method}("/{route_name}", handlers.{route_pascal}Handler)
}}
"""

    test = f"""\
// Auto-generated by api_route_scaffolder.py
package handlers_test

import (
\t"net/http"
\t"net/http/httptest"
\t"testing"
\t"github.com/gin-gonic/gin"
\t"your-module/handlers"
)

func Test{route_pascal}Handler(t *testing.T) {{
\tgin.SetMode(gin.TestMode)
\tr := gin.New()
\tr.{method}("/{route_name}", handlers.{route_pascal}Handler)

\tw := httptest.NewRecorder()
\treq, _ := http.NewRequest("{method}", "/{route_name}", nil)
\tr.ServeHTTP(w, req)

\tif w.Code != http.StatusOK {{
\t\tt.Fatalf("expected 200, got %d", w.Code)
\t}}
}}
"""

    return {"handler": handler, "route": route, "test": test}


def run_scaffolder_express(route_name: str, method: str, out_dir: Path, force: bool):
    templates = build_express_templates(route_name, method)
    targets = {
        out_dir / "controllers" / f"{route_name}.controller.js": templates["controller"],
        out_dir / "services" / f"{route_name}.service.js": templates["service"],
        out_dir / "dto" / f"{route_name}.dto.js": templates["dto"],
        out_dir / "routes" / f"{route_name}.routes.js": templates["route"],
        out_dir / "__tests__" / f"{route_name}.spec.js": templates["test"],
    }
    return targets


def run_scaffolder_fastapi(route_name: str, method: str, out_dir: Path, force: bool):
    route_var = route_name.replace("-", "_")
    templates = build_fastapi_templates(route_name, method)
    targets = {
        out_dir / "routers" / f"{route_var}.py": templates["router"],
        out_dir / "services" / f"{route_var}_service.py": templates["service"],
        out_dir / "schemas" / f"{route_var}.py": templates["schema"],
        out_dir / "tests" / f"test_{route_var}.py": templates["test"],
    }
    return targets


def run_scaffolder_gin(route_name: str, method: str, out_dir: Path, force: bool):
    route_pascal = "".join(p.capitalize() for p in route_name.split("-"))
    templates = build_gin_templates(route_name, method)
    targets = {
        out_dir / "handlers" / f"{route_name}_handler.go": templates["handler"],
        out_dir / "routes" / f"{route_name}_routes.go": templates["route"],
        out_dir / "handlers" / f"{route_name}_handler_test.go": templates["test"],
    }
    return targets


def main():
    parser = argparse.ArgumentParser(description="Generate API route boilerplate files.")
    parser.add_argument("route_name", help="Route name (e.g. users, payment-intents)")
    parser.add_argument("--method", required=True, help="HTTP method (GET, POST, PUT, PATCH, DELETE)")
    parser.add_argument("--framework", default="express",
                        choices=sorted(FRAMEWORKS),
                        help="Target framework (default: express)")
    parser.add_argument("--out-dir", default="src", help="Target source directory (default: src)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args()

    method = args.method.upper()
    if method not in HTTP_METHODS:
        raise SystemExit(f"Unsupported method: {method}. Supported: {', '.join(sorted(HTTP_METHODS))}")

    out_dir = Path(args.out_dir)
    framework = args.framework.lower()

    if framework == "express":
        targets = run_scaffolder_express(args.route_name, method, out_dir, args.force)
    elif framework == "fastapi":
        targets = run_scaffolder_fastapi(args.route_name, method, out_dir, args.force)
    elif framework == "gin":
        targets = run_scaffolder_gin(args.route_name, method, out_dir, args.force)
    else:
        raise SystemExit(f"Unsupported framework: {framework}")

    print(f"🚀 API Route Scaffolder [{framework}]")
    print(f"📁 Output directory: {out_dir}")
    print(f"🎯 Route: /{args.route_name} [{method}]")

    for file_path, content in targets.items():
        if ensure_file(file_path, content, args.force):
            print(f"✅ Wrote: {file_path}")
        else:
            print(f"⏭️  Skipped (exists): {file_path}")


if __name__ == "__main__":
    main()
