#!/usr/bin/env python3
import argparse
from pathlib import Path


HTTP_METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE"}


def ensure_file(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def build_templates(route_name: str, method: str):
    route_var = route_name.replace("-", "_")
    route_pascal = "".join(part.capitalize() for part in route_name.split("-"))
    controller = f"""\
// Auto-generated by api_route_scaffolder.py
const {route_var}Service = require('../services/{route_name}.service');

async function {route_var}Handler(req, res) {{
  const result = await {route_var}Service.{route_var}({{
    params: req.params,
    query: req.query,
    body: req.body
  }});

  return res.status(200).json({{
    data: result,
    error: null,
    meta: {{ route: '{route_name}', method: '{method}' }}
  }});
}}

module.exports = {{ {route_var}Handler }};
"""

    service = f"""\
// Auto-generated by api_route_scaffolder.py
async function {route_var}(input) {{
  // TODO: implement business logic
  return {{
    ok: true,
    input
  }};
}}

module.exports = {{ {route_var} }};
"""

    dto = f"""\
// Auto-generated by api_route_scaffolder.py
const z = require('zod');

const {route_pascal}Dto = z.object({{
  // TODO: define schema
}});

module.exports = {{ {route_pascal}Dto }};
"""

    route = f"""\
// Auto-generated by api_route_scaffolder.py
const router = require('express').Router();
const {{ {route_var}Handler }} = require('../controllers/{route_name}.controller');

router.{method.lower()}('/{route_name}', {route_var}Handler);

module.exports = router;
"""

    test = f"""\
// Auto-generated by api_route_scaffolder.py
describe('{method} /{route_name}', () => {{
  it('returns standardized envelope', async () => {{
    // TODO: add framework-specific integration test
    expect(true).toBe(true);
  }});
}});
"""

    return {
        "controller": controller,
        "service": service,
        "dto": dto,
        "route": route,
        "test": test,
    }


def run_scaffolder(route_name: str, method: str, out_dir: Path, force: bool):
    templates = build_templates(route_name, method)
    targets = {
        out_dir / "controllers" / f"{route_name}.controller.js": templates["controller"],
        out_dir / "services" / f"{route_name}.service.js": templates["service"],
        out_dir / "dto" / f"{route_name}.dto.js": templates["dto"],
        out_dir / "routes" / f"{route_name}.routes.js": templates["route"],
        out_dir / "__tests__" / f"{route_name}.spec.js": templates["test"],
    }

    written = []
    skipped = []
    for file_path, content in targets.items():
        if ensure_file(file_path, content, force):
            written.append(file_path)
        else:
            skipped.append(file_path)

    print("🚀 API Route Scaffolder")
    print(f"📁 Output directory: {out_dir}")
    print(f"🎯 Route: /{route_name} [{method}]")
    for file_path in written:
        print(f"✅ Wrote: {file_path}")
    for file_path in skipped:
        print(f"⏭️ Skipped (exists): {file_path}")


def main():
    parser = argparse.ArgumentParser(description="Generate API route boilerplate files.")
    parser.add_argument("route_name", help="Route name (e.g. users, payment-intents)")
    parser.add_argument(
        "--method",
        required=True,
        help="HTTP method",
    )
    parser.add_argument(
        "--out-dir",
        default="src",
        help="Target source directory (default: src)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files",
    )

    args = parser.parse_args()
    method = args.method.upper()
    if method not in HTTP_METHODS:
        raise SystemExit(f"Unsupported method: {method}. Supported: {', '.join(sorted(HTTP_METHODS))}")

    run_scaffolder(args.route_name, method, Path(args.out_dir), args.force)


if __name__ == "__main__":
    main()
