#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const SRC_EXTENSIONS = new Set(['.jsx', '.tsx', '.html', '.js', '.ts']);
const DATA_TESTID_RE = /data-testid=["']([^"']+)["']/g;

function parseArgs() {
    return {
        src: getArg('--src', 'src'),
        out: getArg('--out', 'cypress/support/pages'),
        framework: getArg('--framework', 'cypress'),
    };
}

function getArg(flag, def) {
    const idx = args.indexOf(flag);
    return idx !== -1 && args[idx + 1] ? args[idx + 1] : def;
}

function walk(dir) {
    const out = [];
    if (!fs.existsSync(dir)) return out;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            if (entry.name === 'node_modules' || entry.name === '.git') continue;
            out.push(...walk(full));
        } else if (SRC_EXTENSIONS.has(path.extname(entry.name).toLowerCase())) {
            out.push(full);
        }
    }
    return out;
}

function toPascal(str) {
    return str.replace(/[-_.\s]+(.)/g, (_, c) => c.toUpperCase())
        .replace(/^(.)/, c => c.toUpperCase());
}

function toCamel(str) {
    const p = toPascal(str);
    return p.charAt(0).toLowerCase() + p.slice(1);
}

function extractTestIds(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    const ids = new Set();
    let m;
    const re = new RegExp(DATA_TESTID_RE.source, DATA_TESTID_RE.flags);
    while ((m = re.exec(content)) !== null) {
        ids.add(m[1]);
    }
    return [...ids];
}

function generateCypressPOM(pageName, testIds) {
    const className = `${pageName}Page`;
    const getters = testIds.map(id => {
        const methodName = toCamel(id.replace(/[^a-zA-Z0-9]+/g, '_'));
        return `  get ${methodName}() { return cy.get('[data-testid="${id}"]'); }`;
    }).join('\n');

    const actions = testIds
        .filter(id => id.toLowerCase().includes('input') || id.toLowerCase().includes('field'))
        .map(id => {
            const methodName = `fill${toPascal(id.replace(/[^a-zA-Z0-9]+/g, '_'))}`;
            return `\n  ${methodName}(value) {\n    this.${toCamel(id.replace(/[^a-zA-Z0-9]+/g, '_'))}.clear().type(value);\n    return this;\n  }`;
        }).join('');

    const submitAction = testIds.find(id => id.toLowerCase().includes('submit') || id.toLowerCase().includes('btn'))
        ? `\n  submit() {\n    this.${toCamel((testIds.find(id => id.toLowerCase().includes('submit') || id.toLowerCase().includes('btn')) || 'submit-btn').replace(/[^a-zA-Z0-9]+/g, '_'))}.click();\n    return this;\n  }` : '';

    return `// Auto-generated by e2e_page_object.js
// data-testid attributes found: ${testIds.length}

class ${className} {
  visit() {
    cy.visit('/${pageName.toLowerCase()}');
    return this;
  }

${getters}${actions}${submitAction}

  verifyLoaded() {
    cy.url().should('include', '/${pageName.toLowerCase()}');
    return this;
  }
}

module.exports = new ${className}();
`;
}

function generatePlaywrightPOM(pageName, testIds) {
    const className = `${pageName}Page`;
    const getters = testIds.map(id => {
        const methodName = toCamel(id.replace(/[^a-zA-Z0-9]+/g, '_'));
        return `  get ${methodName}() { return this.page.getByTestId('${id}'); }`;
    }).join('\n');

    const actions = testIds
        .filter(id => id.toLowerCase().includes('input') || id.toLowerCase().includes('field'))
        .map(id => {
            const methodName = `fill${toPascal(id.replace(/[^a-zA-Z0-9]+/g, '_'))}`;
            return `\n  async ${methodName}(value) {\n    await this.${toCamel(id.replace(/[^a-zA-Z0-9]+/g, '_'))}.fill(value);\n  }`;
        }).join('');

    return `// Auto-generated by e2e_page_object.js (Playwright POM)
// data-testid attributes found: ${testIds.length}

export class ${className} {
  constructor(page) {
    this.page = page;
  }

  async goto() {
    await this.page.goto('/${pageName.toLowerCase()}');
  }

${getters}${actions}

  async verifyLoaded() {
    await this.page.waitForURL('**/${pageName.toLowerCase()}**');
  }
}
`;
}

function main() {
    const opts = parseArgs();

    const srcDir = path.resolve(process.cwd(), opts.src);
    const outDir = path.resolve(process.cwd(), opts.out);
    const framework = opts.framework.toLowerCase();

    if (!fs.existsSync(srcDir)) {
        console.error(`Source directory not found: ${srcDir}`);
        console.log('\nUsage:');
        console.log('  node e2e_page_object.js --src src/ [--out cypress/support/pages] [--framework cypress|playwright]');
        process.exit(1);
    }

    console.log('📝 E2E Page Object Generator');
    console.log(`Source:    ${srcDir}`);
    console.log(`Framework: ${framework}`);
    console.log(`Output:    ${outDir}\n`);

    const files = walk(srcDir);
    const pageMap = new Map(); // pageName → Set<testId>

    for (const filePath of files) {
        const ids = extractTestIds(filePath);
        if (ids.length === 0) continue;

        // Derive page name from file name
        const base = path.basename(filePath, path.extname(filePath));
        const pageName = toPascal(base.replace(/\.(page|screen|view|component)$/i, ''));

        if (!pageMap.has(pageName)) pageMap.set(pageName, new Set());
        for (const id of ids) pageMap.get(pageName).add(id);
    }

    if (pageMap.size === 0) {
        console.log('No data-testid attributes found in source files.');
        console.log('Add data-testid="my-element" to your JSX/HTML to generate page objects.');
        process.exit(0);
    }

    fs.mkdirSync(outDir, { recursive: true });
    let written = 0;

    for (const [pageName, idSet] of pageMap.entries()) {
        const testIds = [...idSet];
        let content, filename;

        if (framework === 'playwright') {
            content = generatePlaywrightPOM(pageName, testIds);
            filename = `${pageName}.page.js`;
        } else {
            content = generateCypressPOM(pageName, testIds);
            filename = `${pageName}.js`;
        }

        const outFile = path.join(outDir, filename);
        fs.writeFileSync(outFile, content, 'utf8');
        console.log(`✅ ${outFile}  [${testIds.length} selectors]`);
        written++;
    }

    console.log(`\nGenerated ${written} page object(s).`);
    console.log('Import them in your test specs:');
    if (framework === 'playwright') {
        console.log(`  import { LoginPage } from '${outDir}/Login.page.js';`);
    } else {
        console.log(`  const loginPage = require('${outDir}/Login.js');`);
    }
}

main();
